Repository offa/android-foss, pull requests merged in 2021-06, with the labels that each got.

#157 Added three apps and removed one
  README.md
Labels: app-proposal, app-update

#158 FlorisBoard added
  README.md
Labels: app-proposal

#159 Add DecSync CC, Remove Clock+
  README.md
Labels: app-proposal, app-removal

#160 add TrackerControl app in Ad Blocker category
  README.md
Labels: app-proposal

#162 Addition
  README.md
Labels: app-proposal

#164 Added 3 apps
  README.md
Labels: app-proposal

#165 Removed 4 apps and added 1 app.
  README.md
Labels: app-proposal, app-removal

#166 Added 1 app to Music & Audio Player
  README.md
Labels: app-proposal
