Repository offa/android-foss, pull requests merged in 2021-08, with the labels that each got.

#175 Added new Call blocker section; Silence app added
  README.md
Labels: enhancement, app-proposal

#178 New apps
  README.md
Labels: app-proposal

#179 Updated Table of Contents
  README.md
Labels: content
