Repository offa/android-foss, pull requests merged in 2022-05, with the labels that each got.

#220 New apps
  README.md
Labels: app-proposal

#221 New apps: Coffee | FitoTrack | Exitrpater | CrossWords
  README.md
Labels: app-proposal

#222 New apps: PixelDroid | PxerStudio | PrivacyBlur | Simon Tatham's Puzzles | Exif Thumbnail Adder
  README.md
Labels: app-proposal, app-update

#223 Removed apps and updated links
  README.md
Labels: app-update, app-removal

#226 Odysee | Atomic - Periodic Table | Monochromatic | Cams
  README.md
Labels: app-proposal, app-update

#227 New apps: Acode
  README.md
Labels: app-proposal, discussion
