Repository offa/android-foss, pull requests merged in 2022-06, with the labels that each got.

#230 Add PCAPdroid
  README.md
Labels: app-proposal

#232 Filester | LinkHub | Retro | OpenTracks | Open Golf | RustDesk | Openreads
  README.md
Labels: app-proposal, app-update

#233 Home Assistant | ObscuraCam | Audio Spectrum Analyzer | Liedgutverzeichnis | Tux Paint | OpenKeychain | Molly
  README.md
Labels: app-proposal, app-update

#234 CTemplar no longer exists
  README.md
Labels: app-removal

#236 Translation apps
  README.md
Labels: app-proposal, content
