Repository offa/android-foss, pull requests merged in 2023-11, with the labels that each got.

#336 Open Sudoku git move
  README.md
Labels: app-update

#337 Forkyz git move
  README.md
Labels: app-update

#339 New app - Call Recorder in Misc category
  README.md
Labels: app-proposal

#341 Add AVNC, ConnectBot, WifiAnalyzer and move Unitto
  README.md
Labels: app-proposal, app-update

#344 Remove abandoned apps
  README.md
Labels: app-removal
