Repository offa/android-foss, pull requests merged in 2023-10, with the labels that each got.

#322 Update FOSS Browser Link
  README.md
Labels: app-update

#320 Add Halma
  README.md
Labels: app-proposal

#321 Add floccus
  README.md
Labels: app-proposal

#324 Replace 'Universal Android Debloater GUI' with 'Android Debloat List'
  README.md
Labels: app-proposal, app-removal

#328 Add SimpMusic
  README.md
Labels: app-proposal

#331 Add Voyager for Lemmy
  README.md
Labels: app-proposal

#332 Updated repository link for Transistor
  README.md
Labels: app-update
