Repository offa/android-foss, pull requests merged in 2024-11, with the labels that each got.

#461 Adds "Box, Box!"
  README.md
Labels: app-proposal

#459 Add Sharing
  README.md
Labels: app-proposal

#462 Make a python script to check wether all categories are sorted or not
  .github/workflows/ci.yml
  ensure_sorted.py
Labels: ci

#463 Make it work for older python versions
  .github/workflows/ci.yml
  ensure_sorted.py
Labels: bug, ci

#464 Fix remaining sorting issues
  README.md
Labels: enhancement, content

#465 Add YAM Launcher
  README.md
Labels: app-proposal

#467 Add encryption category
  README.md
Labels: app-proposal, content
