Repository offa/android-foss, pull requests merged in 2024-07, with the labels that each got.

#396 Added aShell You
  README.md
Labels: app-proposal

#397 Adds 'Easy Diary'
  README.md
Labels: app-proposal

#399 Fixed typo
  tutorials/Install-Rooted-OTA.md
Labels: content

#404 Corrected Birday F-Droid Link
  README.md
Labels: bug

#407 Add Apatch
  README.md
Labels: app-proposal

#408 July24 updates
  README.md
Labels: app-proposal, app-update
