Repository offa/android-foss, pull requests merged in 2024-08, with the labels that each got.

#413 Updates the link for Arcticons
  README.md
Labels: app-update

#412 Updates the link of 'Motion Eye'
  README.md
Labels: app-update

#411 Moves some app to 'Privacy & Security'
  README.md
Labels: content

#410 Rename 'Barcode Scanner' category
  README.md
Labels: enhancement, content

#409 Update the name of DNSFilter
  README.md
Labels: app-update

#416 Moves 'KouChat' to Messaging
  README.md
Labels: content

#417 Update the link of 'Openreads'
  README.md
Labels: app-update

#421 Adds 'Table Habit'
  README.md
Labels: app-proposal, content

#418 Boomee🌸- Addition
  README.md
Labels: app-proposal

#424 Adds 'SD Maid 2/SE'
  README.md
Labels: app-proposal

#419 Moves 'Noice' to Music category
  README.md
Labels: app-update

#426 Adds Rush
  README.md
Labels: app-proposal

#429 Removed unmaintained NekoX and Quacker
  README.md
Labels: app-removal

#428 Added Tools
  README.md
Labels: app-proposal

#427 Adds a HTML version of the repo
  android.svg
  index.html
Labels: enhancement

#431 Remove the unmaintained andOTP app
  README.md
Labels: app-removal

#432 Update Bitwarden repo URL with newer one
  README.md
Labels: app-update

#433 Add Chronos as new app entry
  README.md
Labels: app-proposal

#434 August updates
  README.md
Labels: app-proposal, app-removal
