Repository offa/android-foss, pull requests merged in 2025-02, with the labels that each got.

#487 remove SkyDroid
  README.md
Labels: app-removal

#491 Change addy.io link.
  README.md
Labels: app-update

#493 Replace deprecated app by other project.
  README.md
Labels: app-proposal, app-removal

#494 AppStore Updated
  README.md
Labels: content

#496 Adds 'SherpaTTS' correct F-Droid URL
  README.md
Labels: app-proposal

#498 Educational Game Added
  README.md
Labels: app-proposal
